### PR TITLE
Make Solandra compile with Cassandra 1.1beta2

### PR DESCRIPTION
**Pull request by benmccann**
Here's the code necessary to compile Solandra with Cassandra 1.1beta2

### CODE REVIEW

**Comment by benmccann** [comment]
I don't think this runs correctly, but at least it is a start and will save some time on the upgrade hopefully.

**Comment by benmccann** [comment]
Btw, I noticed the ivy file uses Lucene 3.3.0 and Solr 3.4.0.  We should probably bump the Lucene version to match (or maybe remove it if it's already pulled in by Solr)

**Comment by benmccann** [comment]
I've submitted a few follow-on changes and this seems to be working now.  I'm pretty new to Solandra though, so there could be things I didn't test.

**Comment by tjake** [comment]
Hi Ben thanks for doing this.  With 1.1 we no longer need our version of DecoratedKey either, let me do some testing and I'll get back to you

**Comment by benmccann** [comment]
There's a bug open in the Cassandra JIRA for adding the snaptree and yammer metrics jars to the Cassandra pom, so we won't need to declare them here
https://issues.apache.org/jira/browse/CASSANDRA-3676

**Pull request merged**
