### PR TITLE
Add ability to embed into existing cassandra distribution

### PR DESCRIPTION
**Pull request by tnine**
Hey Jake,
  Re-building our already heavily scripted cassandra deployments wasn't really an option for us.  So, I've created an ant task and a class that will allow the user to add the solandra distribution to the cassandra system.  You'll only want to merge the last 2 commits.  Sorry I didn't have time to rebase into a new branch.

### CODE REVIEW

**Comment by tjake** [comment]
great, thanks

**Comment by tjake** [comment]
This still compiles solandra with the maven repository jar, it should probably use the one you specify when using cassandra-deploy?

**Comment by tnine** [comment]
Good point

**Comment by tjake** [comment]
I can fix this issue...

**Comment by tjake** [comment]
Thanks todd! can you verify its working for you?

**Pull request closed without merging**
